### ISSUE TITLE
Duplicates

### ISSUE THREAD

**Issue by hackdefendr** [redcanaryco/cb-response-surveyor#11]
When running this script I get an output file filled with duplicate entries.  I don't mean 1 or 2 duplicates, I mean like 40 or 50 duplicates.  Making my output file 10 mb before I edit it down.

Is there something that can be done with the script to eliminate duplicates?

**Comment by keithmccammon** [comment]
@hackdefendr Can you please elaborate on the duplicates that you are encountering? Are these th result of things like the same process_name criteria existing in multiple files, resulting in us collecting the exact same data multiple times?
